### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by nadiaparsell** [RameezI/dishscan#1]
Hello,

I was wondering if you have pre-trained weights we can test the model with? Thanks!

**Comment by nadiaparsell** [comment]
Also, what is the directory structure for the images? the dataset is quite big so I want to try running it with the dummy dataset but the script tries to automatically download the entire nutrition5k dataset even when I set the dataset path to dishscan/datasets/nutrition5k/dummy_data/nutrition5k_dataset

**Comment by RameezI** [comment]
Hi @nadiaparsell,

You can use the pre-trained MobileNetV2 model for testing. To do this, follow these steps:

1. Set up the environment by completing steps 1-3 in the README.md.
2. Download the .zip package containing the pretrained model. 
[MobileNetV2.zip](https://github.com/user-attachments/files/16894705/MobileNetV2.zip)

3. Unzip the model directory and run the classification script as shown below:

```
unzip MobileNetV2.zip
python scripts/classify_image_tf.py -m MobileNetV2 -i test_images/dish_1551374783_A.png
```

For more information on the dataset, please see:
https://github.com/google-research-datasets/Nutrition5k

**Comment by nadiaparsell** [comment]
Thank you!
